### ISSUE TITLE
Can we have code highlight in the side bar?

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/the-guild-docs#374]
So it will be `schema` field instead of schema field
![image](https://user-images.githubusercontent.com/7361780/143010212-d6b049ac-6015-414f-8d35-87410db3d09d.png)
![image](https://user-images.githubusercontent.com/7361780/143010237-f42795b1-f391-4fb4-a185-25a5f029eb71.png)

**Comment by PabloSzx** [comment]
check https://github.com/the-guild-org/the-guild-docs/issues/272  https://github.com/the-guild-org/the-guild-docs/pull/273 https://github.com/the-guild-org/the-guild-docs/pull/277 it should be possible, but at the same time we don't want to fill guild-docs with bloated dependencies like react-markdown
