### ISSUE TITLE
Remove Docs collapsable point

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-docs#397]
![image](https://user-images.githubusercontent.com/14338007/143900696-4bfc45f2-0f0c-4a7d-9c2a-e3c82128b6fb.png)

redundant :(

![image](https://user-images.githubusercontent.com/14338007/143900778-1681d49b-d6db-46c7-aa70-05ae622db051.png)

nice and flat!

**Comment by PabloSzx** [comment]
Just modify the routes file, it's not something that guild-docs restricts, I already commented it before on slack

**Comment by PabloSzx** [comment]
this is the example I gave previously:

![image](https://user-images.githubusercontent.com/8672915/143918082-72e821f9-f4cc-48b5-8ff6-f721533a9906.png)
