### ISSUE TITLE
`GenerateRoutes()` should accept some parameter for adding suffix path to sidebar link

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/the-guild-docs#399]
The problem that I want to solve:

- I don't want `Docs` collapsable link like in [envelop](https://www.envelop.dev/docs)
- `GenerateRoutes()` should properly generate sidebar label based on `sidebar_label` or `title`
- each sidebar link should can (or not) start with some prefix, `docs/` in our case

To make it work in [mesh](https://www.graphql-mesh.com/docs/getting-started/introduction) I added some ugly code at the bottom of [`getRoutes()`](https://github.com/Urigo/graphql-mesh/blob/master/website/routes.ts#L75)

@dotansimha made it work in [codegen](https://www.graphql-codegen.com/docs/getting-started) in different way, see [`getRoutes()`](https://github.com/dotansimha/graphql-code-generator/blob/master/website/routes.ts#L7)

**Proposition:** `GenerateRoutes()` should accept some parameter like `suffixPath` and return modified `Routes` so this code

```ts
 GenerateRoutes({
    Routes,
    folderPattern: 'docs',
    ignorePaths: ['extend', 'generated-markdown'],
  });

  return {
    _: Object.fromEntries(
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      Object.entries(Routes._).map(([key, value]) => [`docs/${key}`, value])
    ),
  };
```

can be simplified by this

```ts
  return GenerateRoutes({
    Routes,
    folderPattern: 'docs',
    ignorePaths: ['extend', 'generated-markdown'],
    suffixPath: 'docs/'
  });
```

**Comment by n1ru4l** [comment]
Related? https://github.com/the-guild-org/the-guild-docs/issues/397

**Comment by B2o5T** [comment]
@n1ru4l Yes 👍
