### ISSUE TITLE
fix css issue in `<PackageInstall />`

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/the-guild-docs#400]
- text must be centered
- height must be slower than the current height (current height is 71px)

![image](https://user-images.githubusercontent.com/7361780/143929998-20562efa-aa55-44c1-be26-33cf8d4dadbe.png)

**Comment by elkarouani** [comment]
I checked the page, and I found where that extra space came from.
![image](https://user-images.githubusercontent.com/42010227/145473499-48c80aa1-43ee-401f-96d7-5f2b7117aa32.png)

**Comment by PabloSzx** [comment]
@B2o5T

Do you mean the text to be centered this way?

<img width="684" alt="msedge_4QGXF18iCM" src="https://user-images.githubusercontent.com/8672915/145610862-4dc0176e-a656-47e4-adae-d904b2289b45.png">
<img width="683" alt="msedge_qwl1Kldl4N" src="https://user-images.githubusercontent.com/8672915/145610874-8525d5ec-a0ac-4284-8351-6179d25d3c1f.png">

**Comment by B2o5T** [comment]
Nope :) only vertically

**Comment by elkarouani** [comment]
As I understood, the issue was in the extra space that was above the text

**Comment by PabloSzx** [comment]
> Nope :) only vertically

👍

**Comment by B2o5T** [comment]
Yes, thank you !
