### ISSUE TITLE
Add `devDependency` option to `Package` component 

### ISSUE THREAD

**Issue by saihaj** [the-guild-org/the-guild-docs#433]
> Is it possible to add to a devDependencies?
in yarn something like: yarn add @graphql-yoga/core@0.3.0-canary-352ac0f.0 -D
I guess that it's in @theguild/components where you could have: <PackageInstall devPackages: {['@graphql-yoga/core@0.3.0-canary-352ac0f.0']} />

_Originally by @jycouet at https://github.com/dotansimha/graphql-yoga/pull/754#issue-806789587_

**Comment by PabloSzx** [comment]
It's literally just adding "-D", every package manager supports it

check https://github.com/the-guild-org/the-guild-docs/blame/main/examples/basic/docs/README.mdx#L19

**Comment by PabloSzx** [comment]
an example as comment:

```tsx
<PackageInstall packages={['-D @types/node']} />
```
