### ISSUE TITLE
External links should open in a new tab

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-docs#500]
https://tortilla-hq.slack.com/archives/C0261Q2LJM7/p1645459668109459

**Comment by charlypoly** [comment]
@n1ru4l already done in GraphQL Mesh docs, it just has to be moved in `@the-guild-docs/server` :neckbeard: 
https://github.com/Urigo/graphql-mesh/blob/master/website/src/pages/_app.tsx#L22-L33

**Comment by B2o5T** [comment]
nextra opens links that starts with `https` in new tab, guild-components also, closed as completed
