### ISSUE TITLE
white flash when navigating using dark mode

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-docs#519]
When dark mode is enabled and a route transition is triggered a white flash occurs.

https://user-images.githubusercontent.com/14338007/158561526-42cfd5ec-ce43-4347-a944-ef008ea15168.mp4

**Comment by n1ru4l** [comment]
@B2o5T This issue is still present.

**Comment by n1ru4l** [comment]
https://user-images.githubusercontent.com/14338007/181431743-e8602610-0249-46f7-9d7f-a915dc5a2778.mov

**Comment by B2o5T** [comment]
Yes, for some reason it’s happens only in mesh, let’s keep this issue until I figure out why it’s happens
