### ISSUE TITLE
Open external link in new tab

### ISSUE THREAD

**Issue by charlypoly** [the-guild-org/the-guild-docs#548]
Already applied on Mesh (https://github.com/Urigo/graphql-mesh/pull/3779), I was wondering if we could apply it to all docs.

If a link is internal (starting with `/` or `#`) stay in the same tab, otherwise open a new one.
It would be pretty helpful, especially for tutorials

**Comment by charlypoly** [comment]
@B2o5T @n1ru4l any thoughts?

**Comment by n1ru4l** [comment]
Related to https://github.com/the-guild-org/the-guild-docs/issues/500

**Comment by B2o5T** [comment]
duplicate https://github.com/the-guild-org/the-guild-docs/issues/500
