### ISSUE TITLE
mobile view is broken (navigation)

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-docs#572]
![4A5AEA0A-7702-43C9-8D00-2AB80B73E3E2](https://user-images.githubusercontent.com/14338007/164967329-7fefa3bd-ec16-4e6f-bbe0-a386b2f36c95.jpeg)

**Comment by B2o5T** [comment]
I think I already saw and fixed it in PR of migration to tailwindcss3 in guild-components
