### ISSUE TITLE
Release @guild-docs/server to include `undici` vuln fix

### ISSUE THREAD

**Issue by kevcube** [the-guild-org/the-guild-docs#631]
Undici fix has been included in @guild-docs/server package.json, but a new release has not been published that includes this fix.

Please release @guild-docs/server 4.0.1 including this security fix.

**Comment by B2o5T** [comment]
fixed in [guild-docs@3.1.0](https://github.com/the-guild-org/the-guild-docs/releases/tag/guild-docs%403.1.0)
