### ISSUE TITLE
404 Page does not let you navigate to any useful page

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-docs#649]
When visiting a route that results in a 404 you are kind of stuck. There is no navigation shown only "The Guild" header. Thus you cannot navigate the site you intended to visit.

https://www.graphql-mesh.com/recipes/build-mesh-artifacts

**Comment by B2o5T** [comment]
Yes sir, I already made a PR in Nextra https://github.com/shuding/nextra/pull/607

**Comment by B2o5T** [comment]
Closed as completed https://github.com/shuding/nextra/pull/607
